"""
Paragraph templates: 10 per topic, 4-6 named slots each.

Structure of a template:
  slots  - the 4-6 topic-specific variables this paragraph binds. They are
           bound once per document and recur across its sentences, so the
           paragraph reads as one coherent narrative rather than a bag of
           sentences.
  units  - 7-9 sentence units. Unit 0 is the lead and is always emitted. The
           rest are sampled (5-8 total) and lightly reordered, which is what
           gets documents into the 100-200 word band with real lexical
           variance instead of 200k copies of the same paragraph.

Every template also has access to the shared slots bound for every document:
  {entity} {alias} {peer} {sector} {country} {city} {year} {month_year}
  {designation_program}

The severity register (see SEVERITY_CLOSERS) appends 1-2 sentences whose
vocabulary tracks the document's latent severity. That is the gradient axis:
documents about the same entity and topic separate in embedding space by how
categorically the text asserts a sanctions nexus.
"""
from __future__ import annotations

# --------------------------------------------------------------------------
# Topic-specific slot pools
# --------------------------------------------------------------------------

SLOT_POOLS = {
    "forced_labour": {
        "facility": [
            "a labour-transfer dormitory adjoining the plant",
            "a fenced production campus with on-site accommodation",
            "an industrial park operated by a production and construction division",
            "a satellite workshop co-located with a vocational centre",
            "a spinning mill inside a bonded industrial zone",
            "a processing campus reached by a dedicated shuttle route",
            "a two-shift assembly hall with controlled egress",
        ],
        "commodity": [
            "polysilicon ingots", "cotton lint", "viscose staple fibre",
            "tomato paste", "PVC flooring", "aluminium extrusions",
            "spandex yarn", "calcium carbide", "nitrile gloves",
            "processed seafood", "solar wafers", "combed yarn",
        ],
        "program": [
            "a surplus-labour transfer initiative",
            "a paired-assistance arrangement between two provinces",
            "a poverty-alleviation placement scheme",
            "a vocational skills training programme",
            "a state-brokered seasonal recruitment drive",
            "an inter-regional employment support programme",
        ],
        "mechanism": [
            "recruitment through state-run placement brokers",
            "restrictions on workers' freedom of movement",
            "retention of identity documents by the employer",
            "wage withholding pending completion of a fixed term",
            "compulsory evening political education",
            "quota-based transfers assigned by local government",
            "on-site security screening at dormitory exits",
        ],
        "authority": [
            "the regional labour bureau", "a municipal state-owned assets commission",
            "a production and construction division", "the prefectural human resources office",
            "a county-level poverty alleviation office", "the regional development and reform commission",
        ],
    },
    "export_controls": {
        "item": [
            "five-axis machine tools", "RF power amplifiers", "field-programmable gate arrays",
            "cryogenic vacuum pumps", "deep-ultraviolet photoresist", "oscilloscopes rated above 1 GHz",
            "carbon fibre precursor", "inertial measurement units", "vacuum feedthroughs",
            "electron beam metrology components", "gallium nitride wafers", "ion implantation subsystems",
        ],
        "control": [
            "ECCN 3A090", "ECCN 5A002", "the foreign direct product rule",
            "EAR99 catch-all controls", "Annex I entry 3A001 of the EU dual-use regulation",
            "ECCN 2B201", "the end-use control in section 744.23",
        ],
        "enduser": [
            "an entity already on the BIS Entity List",
            "a designated defence research institute",
            "an end user that failed a post-shipment verification",
            "a state-owned semiconductor fabrication plant",
            "a consignee sharing an address with a listed party",
            "an unverified-list party with no site-visit history",
        ],
        "route": [
            "via a Hong Kong freight forwarder", "through an Almaty consolidator",
            "using a Dubai free-zone re-exporter", "through a Turkish intermediary in Gebze",
            "by air freight routed through a third-country hub",
            "through a Rotterdam-based distributor with no technical staff",
        ],
        "finding": [
            "a licence application denial", "an is-informed letter",
            "a temporary denial order", "an administrative subpoena",
            "a voluntary self-disclosure", "a proposed charging letter",
        ],
    },
    "sanctions_evasion": {
        "vehicle": [
            "a shell company incorporated three weeks before the first shipment",
            "a free-zone entity registered to a shared mailbox address",
            "a dormant trading company reactivated in 2022",
            "a nominee-held holding vehicle with a single director",
            "a mirror company carrying an identical directorate",
            "a successor entity registered the month after designation",
        ],
        "instrument": [
            "third-country letters of credit", "informal value transfer arrangements",
            "crypto-denominated settlement", "back-to-back invoicing",
            "prepayment against forged bills of lading",
            "open-account terms with a related-party consolidator",
        ],
        "counterparty": [
            "a designated bank", "an SDN-listed procurement agent",
            "a blocked defence conglomerate", "a parent under blocking sanctions",
            "an intermediary previously named in an enforcement action",
        ],
        "typology": [
            "invoice under-valuation", "transhipment through a free-trade zone",
            "serial corporate re-registration", "phoenixing of a listed trading arm",
            "layering through three intermediate consignees",
            "declared end-use inconsistent with the consignee's business",
        ],
        "trigger": [
            "a correspondent bank exit", "an OFAC 50 Percent Rule determination",
            "a de-risking decision by the clearing bank",
            "a customs referral following a documentary mismatch",
            "the freezing of a letter of credit at the advising bank",
        ],
    },
    "military_end_use": {
        "platform": [
            "Orlan-10 reconnaissance UAVs", "Kh-101 cruise missiles",
            "Shahed-136 airframes", "T-90M fire control units",
            "Kalibr guidance sections", "S-400 fire control radars",
            "Su-35 airframe subassemblies", "Lancet loitering munitions",
        ],
        "component": [
            "microcontrollers", "fibre-optic gyroscopes", "thermal imaging cores",
            "servo actuators", "radiation-hardened memory", "tantalum capacitors",
            "GNSS anti-jam antennas", "traveling-wave tube amplifiers",
        ],
        "institute": [
            "a state defence research institute", "a military-civil fusion laboratory",
            "a design bureau attached to a state academy",
            "a defence-affiliated university laboratory",
            "a research institute under a national armaments corporation",
        ],
        "contract": [
            "a state defence order", "a classified procurement lot",
            "a ministry framework agreement", "a sole-source armaments contract",
            "an off-budget procurement line",
        ],
        "indicator": [
            "military end-use language in the technical annex",
            "a consignee address shared with a weapons plant",
            "a delivery schedule keyed to a state armaments programme",
            "packaging marked with a military acceptance stamp",
            "a testing requirement referencing a defence standard",
        ],
    },
    "ownership_change": {
        "stake": [
            "a 51 percent interest", "a 49.9 percent interest",
            "a 33.4 percent blocking stake", "a controlling interest",
            "a golden share", "a 24.5 percent interest", "a 75 percent interest",
        ],
        "vehicle": [
            "a Cyprus intermediate holding", "a DMCC free-zone parent",
            "a BVI nominee vehicle", "a Kazakh joint venture",
            "a Singapore holding company with a corporate director",
            "a Dutch cooperative structure",
        ],
        "registry": [
            "the commercial register", "the beneficial ownership register",
            "a leaked shareholder ledger", "an annual return filed late",
            "a notarial share transfer deed", "the free-zone licensing authority record",
        ],
        "trigger": [
            "an OFAC 50 Percent Rule aggregation across two holders",
            "a divestment announced eleven days after designation",
            "a share transfer executed in the week of listing",
            "the appointment of a nominee director resident in a third country",
            "a restructuring that left voting control unchanged",
        ],
        "actor": [
            "a designated individual", "a state asset management company",
            "a designated parent conglomerate", "a sanctioned oligarch's family office",
            "an executive named in the same enforcement action",
        ],
    },
    "maritime": {
        "vessel": [
            "a 2005-built Aframax tanker", "a Panamax bulk carrier",
            "an LR2 product tanker", "a 1998-built Suezmax",
            "a general cargo vessel of 12,400 dwt", "a Handysize bulker",
            "a 2003-built VLCC", "a coastal products tanker",
        ],
        "behaviour": [
            "an AIS transmission gap of 46 hours",
            "a ship-to-ship transfer conducted at anchor",
            "three flag changes within fourteen months",
            "positional data inconsistent with observed draught",
            "a port call absent from the vessel's own log",
            "a loitering pattern outside the territorial sea",
        ],
        "waters": [
            "off Kalamata", "in the Gulf of Oman", "near Riau anchorage",
            "off Fujairah", "in the Kerch Strait approaches",
            "off Ceuta", "in the Malacca Strait eastern approaches",
        ],
        "cargo": [
            "crude oil", "high-sulphur fuel oil", "refined products",
            "thermal coal", "urea", "LPG", "vacuum gasoil",
        ],
        "registry": [
            "the Cameroon flag registry", "a Palau-flagged registration",
            "the Gabon registry", "a Comoros flag", "the San Marino registry",
            "a Barbados registration obtained after delisting elsewhere",
        ],
    },
    "procurement": {
        "tender": [
            "an open tender", "a single-source award", "a restricted framework lot",
            "a negotiated procedure without prior publication",
            "a two-envelope tender with a compressed timetable",
        ],
        "buyer": [
            "a ministry of defence procurement agency", "a state railway operator",
            "a municipal utility", "a national oil company",
            "a provincial public security bureau", "a state grid subsidiary",
        ],
        "good": [
            "telecommunications equipment", "surveillance cameras and analytics software",
            "network switches", "ship-to-shore port cranes",
            "laboratory instrumentation", "armoured personnel vehicles",
            "industrial control systems", "perimeter monitoring systems",
        ],
        "irregularity": [
            "a bid window of four working days", "a single qualified bidder",
            "specifications matching one vendor's datasheet verbatim",
            "an award value 3.1 times the published reference price",
            "an evaluation committee overlapping the winning bidder's advisory board",
            "a technical annex circulated before the tender opened",
        ],
        "value": [
            "USD 4.2 million", "EUR 11.8 million", "USD 780,000",
            "USD 23 million", "EUR 2.6 million", "USD 47 million",
        ],
    },
}


# --------------------------------------------------------------------------
# Paragraph templates
# --------------------------------------------------------------------------

TEMPLATES = {
    "forced_labour": [
        {"id": "fl01", "slots": ["facility", "commodity", "program", "mechanism", "authority"],
         "units": [
             "{entity} operates {facility} in {city}, {country}, producing {commodity} for export.",
             "Workers were placed at the site under {program} administered by {authority}.",
             "Reporting describes {mechanism} as a condition of continued employment.",
             "The {sector} operation supplies at least four downstream manufacturers in third countries.",
             "Shipment records for {year} show consignments of {commodity} moving through two transhipment points.",
             "Auditors were granted access only to the finished-goods warehouse.",
             "A supplier questionnaire returned by {entity} did not disclose the placement arrangement.",
             "Local media coverage from {month_year} describes recruitment quotas assigned to the district.",
             "The company also trades under the name {alias}.",
         ]},
        {"id": "fl02", "slots": ["commodity", "program", "authority", "mechanism", "facility"],
         "units": [
             "A {year} field report links {entity} to {program} covering roughly 1,800 workers.",
             "The transfers were coordinated by {authority} and documented in district employment bulletins.",
             "{entity} processes {commodity} at {facility}.",
             "Workers report {mechanism} following arrival at the site.",
             "The {sector} sector in {city} has been the subject of repeated import-control scrutiny.",
             "Two customer brands suspended orders pending a traceability review.",
             "No independent audit of the dormitory facilities has been published.",
             "Corporate filings list the same registered address as {peer}.",
         ]},
        {"id": "fl03", "slots": ["mechanism", "commodity", "facility", "authority", "program"],
         "units": [
             "Satellite imagery of {facility} shows perimeter construction consistent with controlled-access housing.",
             "{entity} is the registered operator of the site and reports {commodity} output for the {sector} market.",
             "Placement into the facility occurred under {program}.",
             "Former workers describe {mechanism}.",
             "{authority} published a bulletin in {month_year} naming the company as a receiving enterprise.",
             "Downstream buyers in {country} have not published supplier maps below tier two.",
             "The company's export volumes rose sharply in {year}.",
             "A trade association enquiry received no substantive response.",
         ]},
        {"id": "fl04", "slots": ["commodity", "authority", "program", "facility", "mechanism"],
         "units": [
             "Import records show {entity} shipping {commodity} to buyers in three jurisdictions during {year}.",
             "A detention notice cited the company's participation in {program}.",
             "{authority} lists the enterprise among recipients of transferred labour.",
             "The relevant production takes place at {facility}.",
             "Documented practices include {mechanism}.",
             "The {sector} supply chain in this region is difficult to trace because intermediate processing is aggregated.",
             "Counsel for {entity} disputes the characterisation of the placement scheme.",
             "The entity appears in customs data under both its registered name and {alias}.",
         ]},
        {"id": "fl05", "slots": ["program", "mechanism", "commodity", "facility", "authority"],
         "units": [
             "{program} is the mechanism through which workers reached {entity}'s production lines.",
             "Company recruitment notices from {year} reference placement quotas rather than open hiring.",
             "{mechanism} is described in three separate accounts.",
             "The site, {facility}, produces {commodity}.",
             "{authority} is named in the transfer documentation.",
             "The company describes itself as a {sector} manufacturer serving export markets.",
             "A customer audit scheduled for {month_year} was postponed twice.",
             "Shipping documents route goods through an intermediary registered to a different beneficial owner.",
         ]},
        {"id": "fl06", "slots": ["facility", "commodity", "mechanism", "program", "authority"],
         "units": [
             "An investigation published in {month_year} identifies {entity} as an operator of {facility}.",
             "Production at the site centres on {commodity} for the {sector} market.",
             "Workers arrived through {program}.",
             "The report documents {mechanism} and restricted external contact.",
             "{authority} did not respond to written questions.",
             "Two European importers named in the report have since changed suppliers.",
             "The company's website removed references to the facility during {year}.",
             "Corporate records show a shareholding change in the same period.",
         ]},
        {"id": "fl07", "slots": ["commodity", "facility", "authority", "program", "mechanism"],
         "units": [
             "{entity} is a mid-tier {sector} producer whose {commodity} output enters at least two global supply chains.",
             "The company operates {facility}.",
             "{authority} records list it as a participant in {program}.",
             "Interviews describe {mechanism}.",
             "Traceability is complicated because output is blended with material from unaffiliated producers.",
             "A {year} customs advisory flagged shipments from this district for additional documentation.",
             "The company has not published a modern slavery statement.",
             "Alias {alias} appears on bills of lading for the same consignments.",
         ]},
        {"id": "fl08", "slots": ["program", "authority", "facility", "commodity", "mechanism"],
         "units": [
             "District employment data for {year} records placements into {entity} under {program}.",
             "The scheme is administered by {authority}.",
             "Placements were directed to {facility}, where the company processes {commodity}.",
             "Accounts from the site describe {mechanism}.",
             "The {sector} operation employs roughly 2,400 people across two shifts.",
             "Export invoices for the period name a trading intermediary in a third country.",
             "The company disputes that placements were involuntary.",
             "Local reporting from {city} corroborates the transfer numbers.",
         ]},
        {"id": "fl09", "slots": ["mechanism", "facility", "program", "commodity", "authority"],
         "units": [
             "Accounts collected in {year} describe {mechanism} at facilities operated by {entity}.",
             "The principal site is {facility}.",
             "Workers were assigned under {program}.",
             "The company's {commodity} output supplies the {sector} sector.",
             "{authority} published placement statistics consistent with the accounts.",
             "A buyer in {country} suspended purchasing pending clarification.",
             "The company maintains that all employment is voluntary and contractually documented.",
             "Independent verification has not been possible because site access is controlled.",
         ]},
        {"id": "fl10", "slots": ["commodity", "program", "facility", "mechanism", "authority"],
         "units": [
             "Trade data links {entity} to {commodity} shipments totalling several thousand tonnes in {year}.",
             "The producing site is {facility}.",
             "{program} supplied part of the workforce.",
             "Documented conditions include {mechanism}.",
             "{authority} coordinates the placements at prefecture level.",
             "The {sector} category is subject to a rebuttable presumption in one importing jurisdiction.",
             "Two consignments were detained at the border in {month_year}.",
             "The importer of record was a trading company unaffiliated on paper with {entity}.",
         ]},
    ],

    "export_controls": [
        {"id": "ec01", "slots": ["item", "control", "enduser", "route", "finding"],
         "units": [
             "{entity} supplied {item} to {enduser} between {year} and the following year.",
             "The goods are controlled under {control}.",
             "Shipments moved {route}.",
             "The transaction resulted in {finding}.",
             "The company is registered in {city}, {country}, and describes itself as a {sector} distributor.",
             "End-use statements named a civilian research application.",
             "Post-shipment verification was not completed.",
             "The consignee's declared premises are a serviced office.",
         ]},
        {"id": "ec02", "slots": ["control", "item", "route", "enduser", "finding"],
         "units": [
             "A licensing review in {month_year} examined {entity}'s exports of {item}.",
             "{control} applies to the items in question.",
             "The declared end user was {enduser}.",
             "Freight was routed {route}, adding two intermediaries to the chain.",
             "The review concluded with {finding}.",
             "{entity} operates in the {sector} sector and holds no prior licensing history.",
             "Technical specifications in the sales contract exceed the declared application.",
             "The company also appears in shipping records as {alias}.",
         ]},
        {"id": "ec03", "slots": ["item", "enduser", "control", "finding", "route"],
         "units": [
             "{entity} is a {sector} intermediary in {city} that resells {item}.",
             "Customer records identify {enduser} among its buyers.",
             "The items fall under {control}.",
             "Regulators issued {finding} in {year}.",
             "Shipments moved {route}.",
             "The company's technical staff headcount is inconsistent with the equipment it distributes.",
             "Payment for two consignments came from a party not named in the contract.",
             "A related company, {peer}, shares a director.",
         ]},
        {"id": "ec04", "slots": ["route", "item", "control", "enduser", "finding"],
         "units": [
             "Transhipment analysis for {year} shows {item} moving {route} before reaching its final consignee.",
             "{entity} is the exporter of record.",
             "The classification is {control}.",
             "The ultimate recipient is assessed to be {enduser}.",
             "{finding} followed the review.",
             "The company presents as a {sector} trading house with a small warehouse footprint.",
             "Declared unit values are materially below market for the specified grade.",
             "Two of the three consignments were paid in advance.",
         ]},
        {"id": "ec05", "slots": ["control", "finding", "item", "route", "enduser"],
         "units": [
             "{control} was applied to a consignment handled by {entity} in {month_year}.",
             "The goods were {item}.",
             "{finding} was issued to the exporter.",
             "The routing was {route}.",
             "The consignee is {enduser}.",
             "{entity} is a {sector} firm incorporated in {country}.",
             "Correspondence recovered during the review references an alternative delivery address.",
             "The company has since restructured its export operation into a separate legal entity.",
         ]},
        {"id": "ec06", "slots": ["item", "control", "route", "finding", "enduser"],
         "units": [
             "A compliance review at {entity} identified sales of {item} into a controlled destination.",
             "The applicable control is {control}.",
             "Product moved {route}.",
             "The matter concluded with {finding}.",
             "The end user was later assessed as {enduser}.",
             "The company operates in {sector} and reported revenue growth of 60 percent in {year}.",
             "Internal screening did not cover the ultimate consignee.",
             "A second entity at the same address, {peer}, filed near-identical customs declarations.",
         ]},
        {"id": "ec07", "slots": ["enduser", "item", "finding", "control", "route"],
         "units": [
             "{enduser} received {item} through a chain in which {entity} was the last commercial seller.",
             "{finding} was recorded in {year}.",
             "{control} governs the items.",
             "The goods travelled {route}.",
             "{entity} describes itself as a {sector} systems integrator based in {city}.",
             "Order documentation was amended after the initial licence enquiry.",
             "The company declined to identify the ultimate customer.",
             "Bank records show settlement through a third-country correspondent.",
         ]},
        {"id": "ec08", "slots": ["item", "route", "enduser", "control", "finding"],
         "units": [
             "Between {year} and the following year {entity} shipped {item} in eleven consignments.",
             "All eleven moved {route}.",
             "The consignee in each case was {enduser}.",
             "{control} was the operative classification.",
             "The matter resulted in {finding}.",
             "The company is a {sector} reseller with no manufacturing capability.",
             "Its licence applications describe a research end use.",
             "Shipping documents list the consignee under two spellings.",
         ]},
        {"id": "ec09", "slots": ["control", "item", "enduser", "route", "finding"],
         "units": [
             "An enforcement notice published in {month_year} concerns {control}.",
             "{entity} exported {item} in the transactions at issue.",
             "The recipient was {enduser}.",
             "Goods moved {route}.",
             "The outcome was {finding}.",
             "{entity} is registered in {country} in the {sector} sector.",
             "The company's compliance programme was described as documentary rather than substantive.",
             "It continues to trade under {alias}.",
         ]},
        {"id": "ec10", "slots": ["item", "finding", "control", "route", "enduser"],
         "units": [
             "{entity} is the subject of a licensing action concerning {item}.",
             "{finding} was issued in {year}.",
             "The controlling provision is {control}.",
             "Consignments were routed {route}.",
             "The declared end user, {enduser}, could not be verified on site.",
             "The company's {sector} business is concentrated on two customers.",
             "A freight forwarder used in the chain has appeared in three unrelated enforcement matters.",
             "Corporate ownership changed twice during the period under review.",
         ]},
    ],

    "sanctions_evasion": [
        {"id": "se01", "slots": ["vehicle", "instrument", "counterparty", "typology", "trigger"],
         "units": [
             "{entity} is {vehicle} operating in the {sector} sector from {city}.",
             "It transacted with {counterparty} during {year}.",
             "Settlement used {instrument}.",
             "The structure is consistent with {typology}.",
             "{trigger} brought the relationship to attention.",
             "Directors are shared with two other entities at the same address.",
             "Trade documentation describes goods inconsistent with the company's stated licence category.",
             "The company also appears as {alias} in customs filings.",
         ]},
        {"id": "se02", "slots": ["typology", "counterparty", "vehicle", "trigger", "instrument"],
         "units": [
             "Analysis of {year} trade flows identifies {typology} involving {entity}.",
             "The ultimate counterparty is {counterparty}.",
             "{entity} is {vehicle}.",
             "{trigger} interrupted the arrangement.",
             "Payments were structured as {instrument}.",
             "The company reports a {sector} business with two employees and no warehouse.",
             "Its declared turnover for {year} exceeds USD 40 million.",
             "A related company, {peer}, was incorporated the same week.",
         ]},
        {"id": "se03", "slots": ["vehicle", "counterparty", "trigger", "instrument", "typology"],
         "units": [
             "{entity}, {vehicle}, appears in shipping records from {month_year} onward.",
             "Its principal counterparty is {counterparty}.",
             "{trigger} followed a documentary review.",
             "Funds moved via {instrument}.",
             "The pattern matches {typology}.",
             "The company's registered activity is {sector}.",
             "Beneficial ownership resolves to a nominee resident in a third country.",
             "Two bills of lading describe the same container under different cargo descriptions.",
         ]},
        {"id": "se04", "slots": ["instrument", "typology", "vehicle", "counterparty", "trigger"],
         "units": [
             "{instrument} was used to settle at least nine transactions involving {entity}.",
             "The arrangement exhibits {typology}.",
             "{entity} is {vehicle}.",
             "The beneficiary of the flows is {counterparty}.",
             "{trigger} ended the banking relationship in {year}.",
             "The company operates nominally in {sector} from {city}, {country}.",
             "Its licence was issued four months before the first transaction.",
             "No physical premises could be verified at the registered address.",
         ]},
        {"id": "se05", "slots": ["counterparty", "vehicle", "typology", "instrument", "trigger"],
         "units": [
             "Exposure to {counterparty} was identified during a {year} review of {entity}.",
             "{entity} is {vehicle}.",
             "The structure shows {typology}.",
             "Settlement relied on {instrument}.",
             "{trigger} was the proximate cause of the review.",
             "The {sector} classification on the trade licence does not match observed cargo.",
             "Corporate filings were signed by an agent acting for eleven other companies.",
             "The entity continues to appear under the name {alias}.",
         ]},
        {"id": "se06", "slots": ["typology", "vehicle", "trigger", "counterparty", "instrument"],
         "units": [
             "{typology} characterises the trade pattern around {entity} from {year}.",
             "The company is {vehicle}.",
             "{trigger} prompted a suspicious activity filing.",
             "The counterparty on the far side is {counterparty}.",
             "Payment terms were {instrument}.",
             "The declared {sector} business would not require the routing observed.",
             "Container weights recorded at two ports differ by eleven tonnes.",
             "A successor company was registered in {city} shortly afterwards.",
         ]},
        {"id": "se07", "slots": ["vehicle", "instrument", "typology", "trigger", "counterparty"],
         "units": [
             "{entity} was incorporated as {vehicle} and began trading immediately.",
             "It settled transactions through {instrument}.",
             "The trade pattern is consistent with {typology}.",
             "{trigger} occurred in {month_year}.",
             "The ultimate beneficiary is assessed to be {counterparty}.",
             "The company's stated sector is {sector}.",
             "Its filings list a director who resigned from {peer} the previous quarter.",
             "Freight moved through a free zone with limited customs inspection.",
         ]},
        {"id": "se08", "slots": ["trigger", "counterparty", "typology", "vehicle", "instrument"],
         "units": [
             "{trigger} exposed a relationship between {entity} and {counterparty}.",
             "The structure demonstrates {typology}.",
             "{entity} is {vehicle}.",
             "Value moved through {instrument}.",
             "The company presents as a {sector} trader in {country}.",
             "Its customs declarations for {year} name three consignees, all newly registered.",
             "The registered agent has been named in two prior enforcement matters.",
             "Invoices show unit prices well below prevailing market rates.",
         ]},
        {"id": "se09", "slots": ["counterparty", "instrument", "vehicle", "typology", "trigger"],
         "units": [
             "Transactions benefiting {counterparty} were routed through {entity} during {year}.",
             "{instrument} obscured the ultimate payer.",
             "{entity} is {vehicle}.",
             "The typology is {typology}.",
             "{trigger} halted further activity.",
             "The company's {sector} licence was obtained through a corporate services provider.",
             "Its office address is shared with more than forty registered companies.",
             "Trade volumes fell to zero the month after the trigger event.",
         ]},
        {"id": "se10", "slots": ["vehicle", "typology", "counterparty", "instrument", "trigger"],
         "units": [
             "A {month_year} filing identifies {entity} as {vehicle}.",
             "Its trade pattern shows {typology}.",
             "The relationship of concern is with {counterparty}.",
             "Settlement used {instrument}.",
             "{trigger} followed.",
             "The company operates in {sector} and claims regional distribution rights.",
             "Neither warehouse capacity nor staff numbers support the declared volumes.",
             "A near-identically named company, {peer}, files at the same registry.",
         ]},
    ],

    "military_end_use": [
        {"id": "mu01", "slots": ["platform", "component", "institute", "contract", "indicator"],
         "units": [
             "{component} supplied by {entity} were recovered from {platform}.",
             "The parts were traced through a distributor chain terminating at {institute}.",
             "Procurement was funded under {contract}.",
             "Documentation shows {indicator}.",
             "{entity} is a {sector} supplier registered in {city}, {country}.",
             "The company's civilian customer list does not account for the observed volumes.",
             "Serial numbers indicate manufacture in {year}.",
             "The distributor of record has since been dissolved.",
         ]},
        {"id": "mu02", "slots": ["institute", "component", "contract", "platform", "indicator"],
         "units": [
             "{institute} is the end user in a supply chain in which {entity} is a named vendor.",
             "The items are {component}.",
             "{contract} provides the funding line.",
             "Comparable parts have been documented in {platform}.",
             "The technical file contains {indicator}.",
             "{entity} operates in the {sector} sector.",
             "Its export declarations for {year} describe a civilian application.",
             "A second supplier at the same industrial park files similar declarations.",
         ]},
        {"id": "mu03", "slots": ["component", "platform", "indicator", "institute", "contract"],
         "units": [
             "Teardown analysis of {platform} recovered in {year} identified {component}.",
             "One supply route runs through {entity}.",
             "{indicator} appears in the associated procurement file.",
             "The consignee was {institute}.",
             "Funding is attributed to {contract}.",
             "{entity} describes itself as a {sector} distributor with civilian end markets.",
             "Its shipments to the region increased fourfold after {month_year}.",
             "The company has not responded to enquiries.",
         ]},
        {"id": "mu04", "slots": ["contract", "institute", "component", "indicator", "platform"],
         "units": [
             "{contract} names {institute} as executing organisation.",
             "{entity} appears in the associated supplier schedule.",
             "The supplied items are {component}.",
             "{indicator} is documented in the delivery paperwork.",
             "Equivalent parts have been identified in {platform}.",
             "The company's declared sector is {sector}.",
             "It has no published defence customer relationships.",
             "Corporate ownership changed in {year} to a holding company in a third country.",
         ]},
        {"id": "mu05", "slots": ["platform", "indicator", "component", "contract", "institute"],
         "units": [
             "Components consistent with {platform} production were shipped by {entity} during {year}.",
             "{indicator} was recorded at the point of export.",
             "The items are {component}.",
             "Payment was drawn against {contract}.",
             "The receiving organisation is {institute}.",
             "{entity} is a {sector} firm with a single overseas sales office.",
             "Its end-use certificates were signed by a party not registered at the stated address.",
             "The company operates under a second trading name, {alias}.",
         ]},
        {"id": "mu06", "slots": ["component", "institute", "platform", "contract", "indicator"],
         "units": [
             "{entity} is one of four identified suppliers of {component} into a restricted programme.",
             "The programme is run by {institute}.",
             "Output supports {platform}.",
             "{contract} is the procurement instrument.",
             "{indicator} was noted during a documentary review.",
             "The company sits in the {sector} sector and reports civilian revenue only.",
             "Its shipping records for {month_year} show a consignee change mid-transit.",
             "A related party shares the company's bank account signatory.",
         ]},
        {"id": "mu07", "slots": ["indicator", "contract", "component", "platform", "institute"],
         "units": [
             "{indicator} is the strongest evidence of military end use in this case.",
             "The transaction was funded under {contract}.",
             "{entity} supplied {component}.",
             "The parts are consistent with {platform} requirements.",
             "The receiving body is {institute}.",
             "The company's registered activity is {sector}.",
             "Its licence application in {year} declared a metrology application.",
             "The declared application does not match the quantities ordered.",
         ]},
        {"id": "mu08", "slots": ["institute", "platform", "component", "indicator", "contract"],
         "units": [
             "{institute} placed repeat orders with {entity} between {year} and the following year.",
             "The orders concerned {component}.",
             "Comparable parts are used in {platform}.",
             "{indicator} appears across the order set.",
             "{contract} covers the procurement.",
             "{entity} is a {sector} company based in {city}.",
             "It has no export licence on file for the destination.",
             "Two intermediate consignees were added after the first shipment.",
         ]},
        {"id": "mu09", "slots": ["component", "contract", "institute", "platform", "indicator"],
         "units": [
             "Shipments of {component} by {entity} were flagged during a {month_year} review.",
             "The purchase was made under {contract}.",
             "The end user is {institute}.",
             "The items match the specification profile for {platform}.",
             "{indicator} was present in the shipping file.",
             "The company is registered in {country} as a {sector} supplier.",
             "Its declared customers are all in third countries.",
             "Ownership resolves to a holding structure with a nominee director.",
         ]},
        {"id": "mu10", "slots": ["platform", "component", "contract", "indicator", "institute"],
         "units": [
             "Support for {platform} manufacture is the assessed purpose of the procurement.",
             "{entity} supplied {component} into the chain.",
             "{contract} is the funding vehicle.",
             "{indicator} was identified in the technical annex.",
             "{institute} is the ultimate recipient.",
             "The company's {sector} classification understates its role.",
             "Volumes shipped in {year} exceed its prior three years combined.",
             "The supply relationship continued after the first public reporting.",
         ]},
    ],

    "ownership_change": [
        {"id": "oc01", "slots": ["stake", "vehicle", "registry", "trigger", "actor"],
         "units": [
             "{stake} in {entity} was transferred to {vehicle} in {month_year}.",
             "The transfer is recorded in {registry}.",
             "{trigger} makes the transaction relevant to sanctions exposure.",
             "The ultimate controlling party is {actor}.",
             "{entity} operates in the {sector} sector in {city}, {country}.",
             "Board composition did not change following the transfer.",
             "The consideration paid was not disclosed.",
             "The company also files under the name {alias}.",
         ]},
        {"id": "oc02", "slots": ["actor", "stake", "trigger", "vehicle", "registry"],
         "units": [
             "{actor} held {stake} in {entity} until {year}.",
             "{trigger} is documented in the corporate record.",
             "The interest now sits with {vehicle}.",
             "{registry} reflects the change.",
             "The {sector} business continued to operate without interruption.",
             "Two directors associated with the previous owner remain in post.",
             "A management agreement signed at the same time preserved operational control.",
             "The purchaser was incorporated eight weeks before the transaction.",
         ]},
        {"id": "oc03", "slots": ["registry", "stake", "vehicle", "actor", "trigger"],
         "units": [
             "{registry} shows a restructuring of {entity}'s share capital in {month_year}.",
             "{stake} moved to {vehicle}.",
             "The beneficial owner behind the vehicle is {actor}.",
             "{trigger} is the relevant consideration.",
             "The company's {sector} operations in {country} were unaffected.",
             "Bank mandates were not amended.",
             "The registered office moved to a corporate services provider in the same period.",
             "A near-identically named company, {peer}, was registered shortly afterwards.",
         ]},
        {"id": "oc04", "slots": ["trigger", "actor", "stake", "registry", "vehicle"],
         "units": [
             "{trigger} is the basis on which {entity} may be treated as a blocked party.",
             "{actor} retains influence notwithstanding the restructuring.",
             "{stake} is the interest at issue.",
             "{registry} was amended in {year}.",
             "The holding now sits beneath {vehicle}.",
             "The company's {sector} activity is concentrated in {city}.",
             "Aggregating two minority holdings crosses the fifty percent threshold.",
             "Counsel for the company disputes the aggregation.",
         ]},
        {"id": "oc05", "slots": ["stake", "actor", "vehicle", "registry", "trigger"],
         "units": [
             "A transfer of {stake} in {entity} completed in {month_year}.",
             "The disposing party was {actor}.",
             "The acquiring party is {vehicle}.",
             "{registry} records the change without identifying the ultimate owner.",
             "{trigger} is the reason the transaction attracted scrutiny.",
             "The company remains active in {sector}.",
             "Supply contracts were novated rather than renegotiated.",
             "Employee headcount and premises are unchanged.",
         ]},
        {"id": "oc06", "slots": ["vehicle", "registry", "stake", "trigger", "actor"],
         "units": [
             "{vehicle} acquired an interest in {entity} during {year}.",
             "{registry} is the only public source identifying the parties.",
             "The interest amounts to {stake}.",
             "{trigger} applies.",
             "Control is assessed to rest with {actor}.",
             "{entity} is a {sector} operator in {country}.",
             "The transaction was not announced.",
             "A subsequent filing corrected the shareholding percentage downward.",
         ]},
        {"id": "oc07", "slots": ["actor", "vehicle", "trigger", "stake", "registry"],
         "units": [
             "{actor} is the party of concern behind {entity}.",
             "The interest is held through {vehicle}.",
             "{trigger} is documented.",
             "The holding is {stake}.",
             "{registry} was filed late and amended twice.",
             "The company's {sector} business in {city} continued to trade throughout.",
             "A nominee director was appointed in {month_year}.",
             "The company also appears as {alias} on commercial documents.",
         ]},
        {"id": "oc08", "slots": ["registry", "trigger", "vehicle", "actor", "stake"],
         "units": [
             "A review of {registry} in {year} identified changes in the control of {entity}.",
             "{trigger} is the operative test.",
             "The intermediate holder is {vehicle}.",
             "The ultimate party is {actor}.",
             "The interest transferred was {stake}.",
             "The company describes itself as an independent {sector} business.",
             "Its principal customer relationships predate the transfer.",
             "No change of banking counterparty accompanied the restructuring.",
         ]},
        {"id": "oc09", "slots": ["stake", "trigger", "registry", "actor", "vehicle"],
         "units": [
             "{stake} changed hands in a transaction completed in {month_year}.",
             "{trigger} brings {entity} within scope.",
             "{registry} is the documentary basis.",
             "{actor} is the party from whom control derives.",
             "{vehicle} sits between the two.",
             "The {sector} operation is based in {country}.",
             "Two subsidiaries were transferred out of the group in the same week.",
             "The transferee's directors resigned three months later.",
         ]},
        {"id": "oc10", "slots": ["vehicle", "actor", "stake", "registry", "trigger"],
         "units": [
             "{vehicle} is the corporate layer separating {entity} from {actor}.",
             "The interest held is {stake}.",
             "{registry} identifies the immediate but not the ultimate owner.",
             "{trigger} is the analytical basis for treating the exposure as material.",
             "The company operates in {sector} from {city}.",
             "A share pledge granted in {year} is recorded against the same holding.",
             "The pledgee is a bank in a third country.",
             "The structure has been reorganised twice since designation.",
         ]},
    ],

    "maritime": [
        {"id": "mt01", "slots": ["vessel", "behaviour", "waters", "cargo", "registry"],
         "units": [
             "{vessel} managed by {entity} exhibited {behaviour} {waters} in {month_year}.",
             "The vessel was carrying {cargo}.",
             "It is registered with {registry}.",
             "{entity} is a {sector} operator based in {city}, {country}.",
             "Ownership is held through a single-ship company.",
             "Class was withdrawn by one society and reinstated by another in {year}.",
             "Protection and indemnity cover could not be confirmed for the voyage.",
             "The manager also appears in records as {alias}.",
         ]},
        {"id": "mt02", "slots": ["behaviour", "vessel", "cargo", "registry", "waters"],
         "units": [
             "{behaviour} was recorded during a voyage operated by {entity}.",
             "The ship involved was {vessel}.",
             "Cargo was declared as {cargo}.",
             "The vessel flies under {registry}.",
             "The event occurred {waters}.",
             "{entity} manages a fleet of eleven vessels from {city}.",
             "Six of them changed flag in {year}.",
             "Beneficial ownership is opaque at the single-ship company level.",
         ]},
        {"id": "mt03", "slots": ["vessel", "cargo", "registry", "waters", "behaviour"],
         "units": [
             "{vessel}, operated by {entity}, loaded {cargo} in {month_year}.",
             "The vessel is registered under {registry}.",
             "It was subsequently observed {waters}.",
             "{behaviour} accompanied the transit.",
             "The operator is a {sector} company in {country}.",
             "Draught observations are inconsistent with the declared cargo quantity.",
             "The receiving terminal is not named in the vessel's port log.",
             "Insurance documentation was issued by a provider with no prior marine history.",
         ]},
        {"id": "mt04", "slots": ["waters", "behaviour", "vessel", "registry", "cargo"],
         "units": [
             "Activity {waters} in {year} involved vessels under {entity}'s commercial management.",
             "{behaviour} was the principal indicator.",
             "{vessel} is the ship most frequently implicated.",
             "Its flag is {registry}.",
             "Declared cargo was {cargo}.",
             "{entity} operates in {sector} from {city}.",
             "The company was incorporated after the sanctions came into force.",
             "Its fleet was acquired from a single seller over four months.",
         ]},
        {"id": "mt05", "slots": ["registry", "vessel", "behaviour", "cargo", "waters"],
         "units": [
             "{registry} issued documentation for {vessel} in {month_year}.",
             "The ship is managed by {entity}.",
             "{behaviour} was observed shortly afterwards.",
             "The cargo was {cargo}.",
             "The position was {waters}.",
             "{entity} is a {sector} manager with no publicly listed beneficial owner.",
             "Two prior flag states had deregistered the vessel.",
             "The vessel's IMO number appears against three different names since {year}.",
         ]},
        {"id": "mt06", "slots": ["vessel", "waters", "registry", "behaviour", "cargo"],
         "units": [
             "{vessel} completed a voyage {waters} under {entity}'s management.",
             "The flag is {registry}.",
             "{behaviour} occurred mid-voyage.",
             "{cargo} was the declared cargo.",
             "The manager operates in {sector} from {country}.",
             "Charter documentation names a party different from the paying entity.",
             "Bunkering took place at an anchorage rather than a terminal.",
             "The voyage does not appear in the operator's published schedule for {year}.",
         ]},
        {"id": "mt07", "slots": ["cargo", "behaviour", "vessel", "waters", "registry"],
         "units": [
             "A cargo of {cargo} was moved in a manner consistent with sanctions circumvention.",
             "{behaviour} is documented for the voyage.",
             "The carrying vessel was {vessel}, managed by {entity}.",
             "The transfer took place {waters}.",
             "The vessel is registered with {registry}.",
             "{entity} is a {sector} business established in {year}.",
             "It shares a correspondence address with two other ship managers.",
             "Payment for the voyage was made by a third party.",
         ]},
        {"id": "mt08", "slots": ["behaviour", "registry", "vessel", "cargo", "waters"],
         "units": [
             "{behaviour} is the reason {entity}'s fleet came under review in {month_year}.",
             "Several vessels moved to {registry} in the same quarter.",
             "{vessel} is representative of the pattern.",
             "The cargoes were predominantly {cargo}.",
             "Activity concentrated {waters}.",
             "The company operates in {sector} from {city}, {country}.",
             "Its vessels average 21 years of age.",
             "Three were purchased above prevailing scrap-adjusted market value.",
         ]},
        {"id": "mt09", "slots": ["vessel", "registry", "cargo", "waters", "behaviour"],
         "units": [
             "{vessel} is one of five ships under {entity}'s technical management.",
             "All five carry {registry}.",
             "The trade is {cargo}.",
             "Voyages concentrate {waters}.",
             "{behaviour} recurs across the fleet.",
             "{entity} is registered in {country} in the {sector} sector.",
             "Fleet acquisition was financed through an undisclosed lender.",
             "The company's website was registered in {year} and lists no personnel.",
         ]},
        {"id": "mt10", "slots": ["waters", "vessel", "cargo", "behaviour", "registry"],
         "units": [
             "A ship-to-ship operation {waters} was recorded in {month_year}.",
             "{vessel} was one of the participating ships.",
             "{cargo} was transferred.",
             "{behaviour} preceded the operation.",
             "The vessel's flag is {registry}, adopted after a prior deregistration.",
             "{entity} is the commercial manager and operates in {sector}.",
             "The receiving vessel's manager shares a director with {peer}.",
             "Neither ship's AIS record covers the full period of the transfer.",
         ]},
    ],

    "procurement": [
        {"id": "pr01", "slots": ["tender", "buyer", "good", "irregularity", "value"],
         "units": [
             "{entity} won {tender} issued by {buyer} in {month_year}.",
             "The contract covers {good}.",
             "The award value was {value}.",
             "The process featured {irregularity}.",
             "{entity} is a {sector} supplier registered in {city}, {country}.",
             "The company had no prior contracts with this buyer.",
             "Delivery milestones were revised twice after signature.",
             "A competing bidder's challenge was dismissed on procedural grounds.",
         ]},
        {"id": "pr02", "slots": ["buyer", "good", "irregularity", "value", "tender"],
         "units": [
             "{buyer} procured {good} from {entity} during {year}.",
             "The award exhibited {irregularity}.",
             "Contract value was {value}.",
             "The procedure used was {tender}.",
             "{entity} operates in {sector} and was incorporated three years earlier.",
             "Its declared technical capability rests on a single subcontractor.",
             "The subcontractor is registered in a third country.",
             "The buyer has awarded four further contracts to the same supplier since.",
         ]},
        {"id": "pr03", "slots": ["irregularity", "tender", "good", "buyer", "value"],
         "units": [
             "{irregularity} is the principal concern in a {year} award to {entity}.",
             "The procedure was {tender}.",
             "The goods are {good}.",
             "The contracting authority is {buyer}.",
             "The value is {value}.",
             "{entity} is a {sector} company with eleven employees.",
             "Its registered address is a residential building.",
             "Two directors previously held positions with the contracting authority.",
         ]},
        {"id": "pr04", "slots": ["good", "value", "buyer", "tender", "irregularity"],
         "units": [
             "A contract for {good} valued at {value} was awarded to {entity}.",
             "The buyer was {buyer}.",
             "{tender} was the procedure.",
             "{irregularity} is documented in the tender file.",
             "The supplier operates in {sector} from {country}.",
             "Equipment was sourced from a manufacturer subject to export restrictions.",
             "The end use is described only in general terms.",
             "The award was published eleven months after signature.",
         ]},
        {"id": "pr05", "slots": ["tender", "irregularity", "value", "good", "buyer"],
         "units": [
             "{tender} concluded in {month_year} with a single compliant bid.",
             "{irregularity} was recorded.",
             "The value is {value}.",
             "The scope covers {good}.",
             "{buyer} is the contracting authority.",
             "{entity} is a {sector} intermediary rather than a manufacturer.",
             "It holds distribution rights granted in {year}.",
             "The originating manufacturer is in a controlled destination.",
         ]},
        {"id": "pr06", "slots": ["buyer", "irregularity", "tender", "value", "good"],
         "units": [
             "{buyer} has awarded {entity} repeat contracts since {year}.",
             "{irregularity} recurs across the awards.",
             "The most recent used {tender}.",
             "Its value was {value}.",
             "The subject matter is {good}.",
             "{entity} is a {sector} firm in {city}.",
             "Its market share with this buyer exceeds 70 percent.",
             "No competing supplier has been shortlisted since the first award.",
         ]},
        {"id": "pr07", "slots": ["good", "buyer", "tender", "irregularity", "value"],
         "units": [
             "Supply of {good} to {buyer} is the subject of a procurement review.",
             "{entity} is the incumbent supplier.",
             "The award followed {tender}.",
             "{irregularity} was noted.",
             "The contract is worth {value}.",
             "The company sits in the {sector} sector in {country}.",
             "Its bid documentation reproduced the buyer's technical annex verbatim.",
             "Delivery was accepted without independent inspection.",
         ]},
        {"id": "pr08", "slots": ["value", "good", "irregularity", "buyer", "tender"],
         "units": [
             "A {value} contract for {good} was signed in {month_year}.",
             "{irregularity} is evident from the file.",
             "The buyer is {buyer}.",
             "{tender} was the route to market.",
             "{entity} operates in {sector} and was the sole bidder.",
             "The specification named a proprietary component available from one source.",
             "That source is a company under common control with {entity}.",
             "The relationship was not disclosed in the bid.",
         ]},
        {"id": "pr09", "slots": ["irregularity", "buyer", "value", "tender", "good"],
         "units": [
             "{irregularity} characterises a {year} award to {entity}.",
             "{buyer} ran the process.",
             "The value was {value}.",
             "{tender} was used.",
             "The goods were {good}.",
             "The supplier's {sector} classification is recent.",
             "It changed its registered activity code four months before bidding.",
             "The company also trades as {alias}.",
         ]},
        {"id": "pr10", "slots": ["buyer", "tender", "good", "value", "irregularity"],
         "units": [
             "{buyer} issued {tender} for {good} in {month_year}.",
             "{entity} was awarded the contract at {value}.",
             "{irregularity} was subsequently identified.",
             "The supplier is a {sector} business in {city}, {country}.",
             "Its beneficial owner is resident in a third country.",
             "An audit found delivery documentation incomplete for two lots.",
             "The buyer extended the contract without re-tendering in {year}.",
             "A related bidder, {peer}, withdrew before the deadline.",
         ]},
    ],
}


# --------------------------------------------------------------------------
# Severity register
# --------------------------------------------------------------------------
#
# 1-2 of these are appended to every document, chosen by the document's latent
# severity score. This is the gradient: the same entity/topic pair produces
# measurably different embeddings depending on how categorically the text
# asserts a sanctions nexus.

# --------------------------------------------------------------------------
# Shared provenance units
# --------------------------------------------------------------------------
#
# Topic-agnostic sourcing/boilerplate sentences, 2-3 per document. These exist
# for length control (topic templates alone bottom out around 100 words) and
# they are realistic: every document in a risk product carries the same kind of
# provenance furniture. They use only the shared slots.

CONTEXT_UNITS = [
    "This entry was compiled from open-source reporting and commercial registry data.",
    "The record was last reviewed in {month_year}.",
    "Corroboration was sought from two commercial databases covering {country}.",
    "The entity resolves to a single registration in the {country} commercial register.",
    "Screening returned a partial match against a similarly named party in the same sector.",
    "The company has been under periodic review since {year}.",
    "No adverse media in the local language was identified for the period.",
    "The registered address in {city} is shared with at least one other filing entity.",
    "Name matching is complicated by the existence of {peer}, which is unrelated.",
    "The surface form {alias} appears in trade data for the same shipments.",
    "Sector classification follows the counterparty's own {sector} registration.",
    "Filings for {year} were retrieved directly from the registry rather than an aggregator.",
    "Two prior versions of this entry were superseded following clarification.",
    "Identifiers were reconciled against customs records where available.",
    "The assessment covers the entity and its majority-owned subsidiaries.",
    "Coverage of {country} registry data is complete through the end of {year}.",
]


SEVERITY_CLOSERS = {
    "low": [
        "The reporting is single-source and has not been corroborated.",
        "No enforcement action has followed to date.",
        "The relationship appears commercial and no nexus to a designated party is established.",
        "This entry is recorded for monitoring purposes only.",
        "Open-source coverage is thin and largely derivative.",
        "The company has provided a partial response disputing the characterisation.",
        "Nothing in the record supports a listing determination at this stage.",
        "The indicators are weak individually and no pattern has been established.",
    ],
    "mid": [
        "The pattern is consistent with, but not dispositive of, sanctions circumvention.",
        "Two independent sources describe the arrangement in compatible terms.",
        "The exposure warrants enhanced due diligence before any further transaction.",
        "A nexus to a designated party is plausible but not yet documented.",
        "Counterparties should seek written clarification of the ownership chain.",
        "The available record supports elevated risk scoring without a listing conclusion.",
        "Further verification is required before the relationship can be cleared.",
        "The indicators are mutually reinforcing and merit escalation.",
    ],
    "high": [
        "The entity was added to {designation_program} in {month_year}.",
        "Counterparties should treat this as blocked-party exposure.",
        "A direct nexus to a designated party is documented in the record.",
        "The designation captures majority-owned subsidiaries by operation of the fifty percent rule.",
        "Transactions with this party are prohibited for US persons.",
        "The listing was accompanied by an enforcement action against two counterparties.",
        "Existing contracts require immediate review for wind-down obligations.",
        "The evidence supports a determination of deliberate circumvention.",
    ],
}
